language: go
go:
- 1.13.x
script: go test -v && go build
before_deploy: "./create_binaries.sh && ls -la /var/tmp/tailtrigger"
deploy:
  provider: releases
  api_key:
    secure: M+0TCWwx7kkigfk4+To9g8m3QQM/Qi6ah8H8W78uQctB3WImD9oEnLM106sitA6HD2Kwgw8xd3/WrkNQj84JwGvJNiDlTEmRA5nXKz4uWBmWL6+nN3JhFeTVjGYmoRHTnhxh1EMESVhHC1raV8nge015fQgZOgRqGHfC8c89gCFPhbIJ7z2lThd1UEjp63/KA/yTZxfzmwc9p4nfDD8w8CCBwXziWbPPuF5Etobt+05VneeBTly4c7OezwSb4TnWfNClr7L/n+UDJ9dBnDRpR7NdXiD9WyqQf+PTNa53+vM/NeycCOaK83kdxaOL4/TQSqXMUM7XL1FKOtHSqZM+d1WUHI949PQonspjS/7pZWeC7jZtPJmcgfUxUDQ/brtCdtZUnDIfT8gSXIIncs6gjNd9npXG3jNVasyRAopcwTBnu0PP0qVuZpkOGEe8bW92VEYQPHwJu0rGJOAFg9MAqkPvercP52IbRPSKRW/tYSmL/jw4fIFLpJ8dBHmJLKZaKhFzmNdbYKqy5prdg9Rgbsh+JLEfqkqBUtuf5cjz4C5/OzAm20OYUfFpNw/J5uirhbOIHYxLs0//BJqd1lQoOCvTsUWIg1mAxTurZ7Av+Y37AfyRfn/QUO9ElP3bYBZ1HYK5kbjIzpCfzdgEiWF0lZoQ3OOuexwj9lr0LbxeytI=
  file_glob: true
  file: /var/tmp/tailtrigger/*
  skip_cleanup: true
  on:
    repo: nxadm/tailtrigger
    tags: true
    branches:
      only:
      - /^v\d+\.\d+\.\d+$/    
